databases:
  - prefix: "/Users/cnicolaou"
    location: ./local-database/cnicolaou
  - prefix: "/Users/cnicolaou/Dropbox (Personal)"
    location: ./local-database/dropbox
  - prefix: "/usr/local"
    location: ./local-database/usr-local
  - prefix: "/tmp"
    location: ./local-database/tmp
parameters:
  - type: "block"
    prefix: "/"
    block_size: 4096
  - type: "block"
    prefix: "/labs/asbhatt"
    block_size: 4096
exclusions:
  - prefix: "/Users/cnicolaou"
    regexps:
      - ".DS_Store$"
