databases:
  - prefix: "/Users/cnicolaou"
    type: "local"
    directory: ./local-database/home
  - prefix: "/Users/cnicolaou/Dropbox (Personal)"
    type: "local"
    directory: ./local-database/dropbox
  - prefix: "/Users/cnicolaou/Dropbox (Personal)/github.com/cloudengio/idu"
    type: "local"
    directory: ./local-database/idu
  - prefix: "/usr/local"
    type: "local"
    directory: ./local-database/usr-local
  - prefix: "/tmp"
    type: "local"
    directory: ./local-database/tmp
layouts:
  - type: "block"
    prefix: "/"
    block_size: 4096
  - type: "block"
    prefix: "/labs/asbhatt"
    block_size: 4096
exclusions:
  - prefix: "/Users/cnicolaou"
    regexps:
      - ".DS_Store$"
