jobs:
  test:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - run:
          name: test
          command: |
            go test --covermode=atomic -vet=off -race ./...

  lint:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run:
          name: downloads
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
            go get github.com/matthewloring/validjson/cmd/validjson
            go install -x github.com/matthewloring/validjson/cmd/validjson
      - run:
          name: lint
          command: |
            golangci-lint run ./...
            validjson ./...

version: 2.1
workflows:
  main:
    jobs:
      - test
      - lint
