name: go-linux

on:   
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-test-lint:
    uses: cloudengio/.github/.github/workflows/go-test-lint.yml@main
    with:
      go-versions: ["1.22.x", "1.23.x"]
      os-version: ubuntu-latest
